import { Check, CreditCard, ExternalLink, ShieldCheck } from 'lucide-react'
import { useState } from 'react'
import { Badge, Button, Card, PageHeader } from '../components/ui'
import { usePortfolio } from '../context/PortfolioContext'
import { config, edgeUrl } from '../lib/config'
import { billingPlans as plans } from '../lib/billing'

export function Billing(){
  const {session,demo,setNotice}=usePortfolio();const [annual,setAnnual]=useState(true);const [busy,setBusy]=useState('')
  const requestBilling=async(endpoint:string,body:Record<string,string>)=>{if(demo||!session){setNotice({tone:'info',message:'Sign in with your MASTERDECK account to use billing.'});return}setBusy(endpoint);try{const response=await fetch(edgeUrl(endpoint),{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:config.dataKey,'Content-Type':'application/json'},body:JSON.stringify({...body,returnUrl:window.location.origin})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Stripe billing is not configured yet.');window.location.assign(data.url)}catch(error){setNotice({tone:'error',message:error instanceof Error?error.message:'Billing could not open.'})}finally{setBusy('')}}
  const checkout=(id:string)=>requestBilling('stripe-checkout',{plan:id,interval:annual?'annual':'monthly'})
  return <><PageHeader title="Plans & billing" description="Full portfolio intelligence, priced 30% below comparable Navexa annual plans." actions={<div className="page-actions"><Button variant="ghost" icon={ExternalLink} busy={busy==='stripe-portal'} onClick={()=>requestBilling('stripe-portal',{})}>Manage billing</Button><Badge tone="success">Payments secured by Stripe</Badge></div>}/><div className="billing-toggle"><button className={!annual?'active':''} onClick={()=>setAnnual(false)}>Monthly</button><button className={annual?'active':''} onClick={()=>setAnnual(true)}>Annual <span>save 22%</span></button></div><div className="pricing-grid">{plans.map(p=><Card key={p.id} className={`pricing-card ${p.featured?'featured':''}`}>{p.featured&&<Badge tone="success">Recommended</Badge>}<h2>{p.name}</h2><p>Up to <strong>{p.portfolios}</strong> {p.portfolios===1?'portfolio':'portfolios'}</p><div className="plan-price"><strong>${annual?p.annual:p.monthly}</strong><span>AUD / month</span></div><small>{annual?`$${p.annual*12} billed annually`:'Billed monthly. Cancel anytime.'}</small><Button variant={p.featured?'primary':'secondary'} icon={CreditCard} busy={busy===p.id} onClick={()=>checkout(p.id)}>Choose {p.name}</Button><ul>{p.features.map(f=><li key={f}><Check/>{f}</li>)}</ul></Card>)}</div><div className="billing-trust"><span><ShieldCheck/>Stripe-hosted checkout</span><span><CreditCard/>Card details never touch MASTERDECK</span><span><ExternalLink/>Customer billing portal included</span></div></>
}
