import { MetricSurface } from '../components/MetricSurface'
import { ArrowDown, ArrowUp, CalendarDays, Check, ChevronDown, ChevronRight, Columns3, Download, EyeOff, Filter, GripVertical, LockKeyhole, MoreHorizontal, Printer, RefreshCw, Search, TrendingUp, X } from 'lucide-react'
import { Fragment, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { usePortfolio } from '../context/PortfolioContext'
import { holdingCapitalGain, holdingCurrencyGain, incomeTransactions, summarisePortfolio } from '../lib/portfolio'
import { marketFreshnessLabel } from '../lib/marketDataApi'
import { date, downloadCsv, money } from '../lib/format'
import { EmptyState, MotionDialogSurface, MotionPopover, PrivateMoney } from '../components/ui'
import { PortfolioSetupGuide } from '../components/PortfolioSetupGuide'
import { HoldingLogo } from '../components/HoldingLogo'
import { HoldingNavigationRow } from '../components/HoldingNavigation'
import { useDailyPortfolioHistory } from '../hooks/useDailyPortfolioHistory'
import { FinanceChart } from '../components/FinanceChart'
import type { Position, Transaction } from '../types'

type GroupBy = 'Exchange' | 'Sector' | 'Currency' | 'Holding Type'
type SortKey = 'symbol' | ColumnKey
type FilterField = '' | GroupBy
type PortfolioFilter = { id: number; field: FilterField; operator: 'is' | 'is not'; value: string }
type ColumnKey = 'price' | 'average_cost' | 'quantity' | 'value' | 'capital_gain' | 'capital_gain_pct' | 'income_return' | 'income_return_pct' | 'currency_gain' | 'currency_gain_pct' | 'total_return' | 'total_return_pct'

const rangeOptions: Record<string, number> = {
  Today: 1, 'Today (from yesterday open)': 2, 'Last 7 Days': 7, 'Last 30 Days': 30,
  'This Month': 31, 'Last Month': 62, 'Current calendar year': 366, 'Previous calendar year': 732,
  'Last 6 Months': 183, 'Last 1 Year': 366, 'This Financial year': 366, 'Last Financial year': 732, 'All Time': Infinity,
}

const columns: { key: ColumnKey; label: string; defaultVisible: boolean }[] = [
  { key: 'price', label: 'Price', defaultVisible: true }, { key: 'average_cost', label: 'Avg Buy Price', defaultVisible: false },
  { key: 'quantity', label: 'Quantity', defaultVisible: true }, { key: 'value', label: 'Value', defaultVisible: true },
  { key: 'capital_gain', label: 'Capital Gain', defaultVisible: true }, { key: 'capital_gain_pct', label: 'Capital Gain %', defaultVisible: true },
  { key: 'income_return', label: 'Income Return', defaultVisible: false }, { key: 'income_return_pct', label: 'Income Return %', defaultVisible: false },
  { key: 'currency_gain', label: 'Currency Gain', defaultVisible: false }, { key: 'currency_gain_pct', label: 'Currency Gain %', defaultVisible: false },
  { key: 'total_return', label: 'Total Return', defaultVisible: true }, { key: 'total_return_pct', label: 'Total Return %', defaultVisible: true },
]

const displayPercent = (value: number) => `${Number(value || 0).toFixed(2)}%`
const groupValue = (item: Position, groupBy: GroupBy) => ({ Exchange: item.market, Sector: item.sector, Currency: item.currency, 'Holding Type': item.asset_class }[groupBy] || 'Other')
const positiveColumn = (key: ColumnKey) => ['capital_gain', 'capital_gain_pct', 'total_return', 'total_return_pct'].includes(key)
const cellValue = (item: Position, key: ColumnKey, income = 0) => ({
  price: money(item.current_price, item.currency, item.currency === 'AUD' ? 3 : 2), average_cost: money(item.average_cost, item.currency, 2),
  quantity: item.quantity.toLocaleString('en-AU', { maximumFractionDigits: 4 }), value: money(item.value_aud, 'AUD', 2),
  capital_gain: money(holdingCapitalGain(item), 'AUD', 2), capital_gain_pct: displayPercent(item.return_pct), income_return: money(income, 'AUD', 2),
  income_return_pct: displayPercent(item.cost_aud ? income/item.cost_aud*100 : 0),
  currency_gain: holdingCurrencyGain(item) === null ? 'Not available' : money(holdingCurrencyGain(item)!, 'AUD', 2),
  currency_gain_pct: holdingCurrencyGain(item) === null || !item.cost_aud ? 'Not available' : displayPercent(holdingCurrencyGain(item)!/item.cost_aud*100),
  total_return: money(item.unrealised_gain_aud + income, 'AUD', 2), total_return_pct: displayPercent(item.cost_aud ? (item.unrealised_gain_aud + income)/item.cost_aud*100 : 0),
}[key])

function HoldingRow({ item, income, visibleColumns, menuOpen, onMenu }: { item: Position; income: number; visibleColumns: ColumnKey[]; menuOpen: boolean; onMenu: () => void }) {
  const navigate = useNavigate()
  return <HoldingNavigationRow symbol={item.symbol}>
    <td className="portfolio-symbol"><button className="holding-link" onClick={() => navigate(`/app/holdings/${encodeURIComponent(item.symbol)}`)}><HoldingLogo symbol={item.symbol}/><span><strong>{item.symbol}</strong><small>{item.name || item.account_name}</small></span></button></td>
    {visibleColumns.map((key) => <td key={key} className={`numeric ${['value','capital_gain','income_return','currency_gain','total_return'].includes(key) ? 'private-value' : ''} ${positiveColumn(key) ? (item.unrealised_gain_aud >= 0 ? 'positive' : 'negative') : ''}`}><span className={key === 'price' ? 'holding-price' : ''}>{cellValue(item, key, income)}</span></td>)}
    <td className="row-menu"><button aria-label={`Actions for ${item.symbol}`} aria-expanded={menuOpen} onClick={onMenu}><MoreHorizontal size={15}/></button><MotionPopover open={menuOpen} className="row-menu-popover"><button onClick={() => navigate(`/app/holdings/${encodeURIComponent(item.symbol)}`)}>View holding</button><button onClick={() => navigate(`/app/transactions?symbol=${encodeURIComponent(item.symbol)}`)}>View transactions</button></MotionPopover></td>
  </HoldingNavigationRow>
}

function recordedHoldingIncome(item: Position, transactions: Transaction[]) { return incomeTransactions(transactions).filter(t => t.symbol === item.symbol && t.provider === item.provider && t.account_name === item.account_name).reduce((sum,t) => sum + Math.abs(t.amount*t.fx_rate),0) }

function sortableHoldingValue(item: Position, key: SortKey, transactions: Transaction[]) {
  if (key === 'symbol') return item.symbol
  const income = recordedHoldingIncome(item,transactions)
  return ({ price:item.current_price, average_cost:item.average_cost, quantity:item.quantity, value:item.value_aud, capital_gain:holdingCapitalGain(item), capital_gain_pct:item.return_pct, income_return:income, income_return_pct:item.cost_aud ? income/item.cost_aud*100 : 0, currency_gain:holdingCurrencyGain(item) || 0, currency_gain_pct:item.cost_aud ? (holdingCurrencyGain(item) || 0)/item.cost_aud*100 : 0, total_return:item.unrealised_gain_aud+income, total_return_pct:item.cost_aud ? (item.unrealised_gain_aud+income)/item.cost_aud*100 : 0 })[key]
}

export function Overview() {
  const { bundle, action, refreshQuotes, marketData } = usePortfolio()
  const history = useDailyPortfolioHistory(bundle)
  const snapshots = history.snapshots
  const [query, setQuery] = useState(''); const [range, setRange] = useState('All Time'); const [rangeOpen, setRangeOpen] = useState(false); const [customStart, setCustomStart] = useState(snapshots[0]?.date || ''); const [customEnd, setCustomEnd] = useState(snapshots.at(-1)?.date || '')
  const [positionsOpen, setPositionsOpen] = useState(false); const [positionsMode, setPositionsMode] = useState<'All Positions' | 'Open Positions Only'>('All Positions')
  const [filterOpen, setFilterOpen] = useState(false); const [filters, setFilters] = useState<PortfolioFilter[]>([])
  const [valueMode, setValueMode] = useState<'Amount' | 'Percent'>('Amount'); const [chartType, setChartType] = useState<'Line' | 'Bar'>('Line'); const [granularity, setGranularity] = useState<'D' | 'M' | 'Y'>('D')
  const [groupBy, setGroupBy] = useState<GroupBy>('Exchange'); const [groupOpen, setGroupOpen] = useState(false); const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set())
  const [hideClosed, setHideClosed] = useState(false); const [columnsOpen, setColumnsOpen] = useState(false); const [columnSearch, setColumnSearch] = useState('')
  const defaultColumns = useMemo(() => columns.filter((item) => item.defaultVisible).map((item) => item.key), [])
  const [visibleColumns, setVisibleColumns] = useState<ColumnKey[]>(defaultColumns); const [pendingColumns, setPendingColumns] = useState<ColumnKey[]>(defaultColumns); const [draggedColumn, setDraggedColumn] = useState<ColumnKey | null>(null); const [exportOpen, setExportOpen] = useState(false)
  const [sort, setSort] = useState<{ key: SortKey; direction: 'ascending' | 'descending' }>({ key: 'symbol', direction: 'ascending' }); const [rowMenu, setRowMenu] = useState<string | null>(null)
  const [activeMetric, setActiveMetric] = useState<'portfolio' | 'capital' | 'income' | 'currency' | 'total'>('portfolio')
  const summary = useMemo(() => summarisePortfolio(bundle), [bundle])
  const chartData = useMemo(() => { const latest = snapshots.at(-1)?.date ? new Date(snapshots.at(-1)!.date).getTime() : 0; const days = rangeOptions[range] ?? Infinity; const rows = snapshots.filter((item) => { const time = new Date(item.date).getTime(); if (range === 'Custom range') return (!customStart || time >= new Date(customStart).getTime()) && (!customEnd || time <= new Date(customEnd).getTime()); return days === Infinity || time >= latest - days * 86_400_000 }); const first = rows[0]?.value_aud || 0; return rows.map((item, index) => ({ ...item, percent: first ? ((item.value_aud - first) / first) * 100 : 0, change: index ? item.value_aud - rows[index - 1].value_aud : 0 })) }, [snapshots, customEnd, customStart, range])
  const renderedChartData = useMemo(() => {
    const values = chartData.map(item => activeMetric === 'income' ? incomeTransactions(bundle.transactions).filter(t => new Date(t.date).getTime() <= new Date(item.date).getTime()).reduce((sum,t) => sum + Math.abs(t.amount*t.fx_rate),0) : item.value_aud)
    const metricRows = chartData.map((item,index) => ({ ...item, value_aud: values[index], percent: activeMetric === 'income' ? (summary.cost ? values[index]/summary.cost*100 : 0) : item.percent, change: index ? values[index]-values[index-1] : 0 }))
    if (chartType !== 'Bar' || granularity === 'D') return metricRows
    const buckets = new Map<string, (typeof metricRows)[number]>()
    metricRows.forEach((item) => { const parsed = new Date(item.date); const key = granularity === 'Y' ? String(parsed.getFullYear()) : `${parsed.getFullYear()}-${parsed.getMonth()}`; buckets.set(key, item) })
    const rows = [...buckets.values()]
    return rows.map((item, index) => ({ ...item, change: index ? item.value_aud - rows[index - 1].value_aud : 0 }))
  }, [activeMetric, chartData, chartType, granularity, summary.cost, bundle.transactions])
  const filtered = useMemo(() => bundle.holdings.filter((item) => { if (!`${item.symbol} ${item.name} ${item.market} ${item.account_name}`.toLowerCase().includes(query.toLowerCase())) return false; if ((positionsMode === 'Open Positions Only' || hideClosed) && item.quantity <= 0) return false; return filters.every((filter) => { if (!filter.field || !filter.value) return true; const matches = groupValue(item, filter.field).toLowerCase() === filter.value.toLowerCase(); return filter.operator === 'is' ? matches : !matches }) }), [bundle.holdings, filters, hideClosed, positionsMode, query])
  const groups = useMemo(() => { const output = new Map<string, Position[]>(); filtered.forEach((item) => { const key = groupValue(item, groupBy); output.set(key, [...(output.get(key) || []), item]) }); const direction = sort.direction === 'ascending' ? 1 : -1; return [...output.entries()].map(([key, items]) => [key, [...items].sort((a, b) => { const av = sortableHoldingValue(a,sort.key,bundle.transactions); const bv = sortableHoldingValue(b,sort.key,bundle.transactions); return (typeof av === 'string' ? av.localeCompare(String(bv)) : Number(av) - Number(bv)) * direction })] as [string, Position[]]) }, [filtered, groupBy, sort, bundle.transactions])
  const totalReturn = summary.unrealised + summary.income; const totalReturnPct = summary.cost ? (totalReturn / summary.cost) * 100 : 0
  const metrics = [
    { id: 'portfolio' as const, label: 'Portfolio Value', value: summary.total, percent: totalReturnPct },
    { id: 'capital' as const, label: 'Capital Gain', value: summary.capitalGain, percent: summary.cost ? summary.capitalGain / summary.cost * 100 : 0 },
    { id: 'income' as const, label: 'Income Return', value: summary.income, percent: summary.cost ? summary.income / summary.cost * 100 : 0 },
    { id: 'currency' as const, label: 'Currency Gain', value: summary.currencyGain, percent: summary.cost ? summary.currencyGain / summary.cost * 100 : 0 },
    { id: 'total' as const, label: 'Total Return', value: totalReturn, percent: totalReturnPct },
  ]
  const isFirstRun = !bundle.holdings.length && !bundle.transactions.length && !bundle.connections.length
  const addFilter = () => setFilters((current) => [...current, { id: Date.now(), field: '', operator: 'is', value: '' }]); const updateFilter = (id: number, changes: Partial<PortfolioFilter>) => setFilters((current) => current.map((item) => item.id === id ? { ...item, ...changes } : item))
  const toggleSort = (key: SortKey) => setSort((current) => ({ key, direction: current.key === key && current.direction === 'ascending' ? 'descending' : 'ascending' })); const togglePendingColumn = (key: ColumnKey) => setPendingColumns((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])
  const reorderColumn = (target: ColumnKey) => { if (!draggedColumn || draggedColumn === target || !pendingColumns.includes(draggedColumn) || !pendingColumns.includes(target)) return; setPendingColumns((current) => { const next = current.filter((item) => item !== draggedColumn); next.splice(next.indexOf(target), 0, draggedColumn); return next }); setDraggedColumn(null) }
  const exportHoldings = () => downloadCsv('masterdeck-holdings.csv', ['Symbol', 'Market', 'Price', 'Quantity', 'Value AUD', 'Capital gain AUD', 'Capital gain %'], filtered.map((item) => [item.symbol, item.market, item.current_price, item.quantity, item.value_aud, item.unrealised_gain_aud, item.return_pct])); const getFilterValues = (field: FilterField) => field ? [...new Set(bundle.holdings.map((item) => groupValue(item, field)))].sort() : []
  const headerFor = (key: ColumnKey) => { const def = columns.find((item) => item.key === key)!; const sortKey: SortKey = key; return <th key={key} className="numeric" aria-sort={sort.key === sortKey ? sort.direction : 'none'}><button onClick={() => toggleSort(sortKey)}>{def.label}{sort.key === sortKey ? (sort.direction === 'ascending' ? <ArrowUp size={11}/> : <ArrowDown size={11}/>) : null}</button></th> }

  if (isFirstRun) return <div className="portfolio-page portfolio-first-run"><PortfolioSetupGuide /></div>

  return <div className="portfolio-page">
    <h1 className="visually-hidden">Portfolio overview</h1>
    <div className="portfolio-toolbar"><label className="portfolio-filter"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter holdings…" aria-label="Filter holdings"/></label>
      <div className="control-popover-wrap"><button className="with-tooltip" data-tooltip={`${snapshots[0]?.date ? date(snapshots[0].date,{day:'2-digit',month:'2-digit',year:'numeric'}) : 'Start'} – ${snapshots.at(-1)?.date ? date(snapshots.at(-1)!.date,{day:'2-digit',month:'2-digit',year:'numeric'}) : 'Today'}`} aria-label={range} aria-expanded={rangeOpen} onClick={() => setRangeOpen(!rangeOpen)}><CalendarDays size={15}/>{range}<ChevronDown size={13}/></button><MotionPopover open={rangeOpen} className="control-menu range-menu" role="menu" origin="top left">{[...Object.keys(rangeOptions), 'Custom range'].map((item) => <button key={item} className={range === item ? 'selected' : ''} onClick={() => { setRange(item); setRangeOpen(false) }}>{range === item && <Check size={13}/>}<span>{item}</span></button>)}</MotionPopover></div>
      <div className="control-popover-wrap filter-popover"><button className={`${filterOpen ? 'active-control ' : ''}with-tooltip`} data-tooltip="Filter Holdings" aria-label="Filter" aria-expanded={filterOpen} onClick={() => { setFilterOpen(!filterOpen); if (!filters.length) addFilter() }}><Filter size={15}/>Filter{filters.filter((item) => item.field && item.value).length > 0 && <span className="filter-count">{filters.filter((item) => item.field && item.value).length}</span>}</button><MotionPopover open={filterOpen} className="filter-builder" role="region" ariaLabel="Portfolio filters" origin="top left"><span>Where</span>{filters.map((filter) => <div className="filter-row" key={filter.id}><select aria-label="Filter field" value={filter.field} onChange={(event) => updateFilter(filter.id, { field: event.target.value as FilterField, value: '' })}><option value="">Select field…</option>{(['Exchange','Sector','Currency','Holding Type'] as GroupBy[]).map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter operator" disabled={!filter.field} value={filter.operator} onChange={(event) => updateFilter(filter.id, { operator: event.target.value as PortfolioFilter['operator'] })}><option>is</option><option>is not</option></select><select aria-label="Filter value" disabled={!filter.field} value={filter.value} onChange={(event) => updateFilter(filter.id, { value: event.target.value })}><option value="">Select value…</option>{getFilterValues(filter.field).map((item) => <option key={item}>{item}</option>)}</select><button aria-label="Remove filter" onClick={() => setFilters((current) => current.filter((item) => item.id !== filter.id))}><X size={14}/></button></div>)}<button className="add-filter" onClick={addFilter}>+ Add filter</button></MotionPopover></div>
      <div className="control-popover-wrap"><button className="with-tooltip tooltip-wide" data-tooltip="Choose whether page totals, returns, and table rows include closed positions." aria-label={positionsMode} aria-expanded={positionsOpen} onClick={() => setPositionsOpen(!positionsOpen)}>{positionsMode}<ChevronDown size={13}/></button><MotionPopover open={positionsOpen} className="control-menu">{(['All Positions','Open Positions Only'] as const).map((item) => <button key={item} onClick={() => { setPositionsMode(item); setPositionsOpen(false) }}>{positionsMode === item && <Check size={13}/>}<span>{item}</span></button>)}</MotionPopover></div>
      <span className={`market-data-summary state-${marketData.status}`} title={bundle.demo ? 'Sample portfolio data' : marketData.message || marketFreshnessLabel(marketData)}><i/>{bundle.demo ? 'Demo data' : marketFreshnessLabel(marketData)}</span><button className="refresh-market" onClick={() => refreshQuotes()} disabled={action === 'refresh-quotes'}><RefreshCw className={action === 'refresh-quotes' ? 'spin' : ''} size={15}/>{action === 'refresh-quotes' ? 'Refreshing' : 'Refresh'}</button></div>
    {range === 'Custom range' && <section className="custom-range" aria-label="Custom date range"><label>From<input type="date" value={customStart} max={customEnd || undefined} onChange={(event) => setCustomStart(event.target.value)}/></label><label>To<input type="date" value={customEnd} min={customStart || undefined} onChange={(event) => setCustomEnd(event.target.value)}/></label></section>}
    <div className="portfolio-metrics" role="tablist" aria-label="Portfolio return metric">{metrics.map((metric) => <MetricSurface key={metric.id} label={metric.label} exact={money(metric.value, 'AUD', 2)} selected={activeMetric === metric.id} onSelect={() => setActiveMetric(metric.id)}><strong><PrivateMoney value={metric.value} digits={2}/></strong><small className={metric.percent > 0 ? 'positive' : metric.percent < 0 ? 'negative' : ''}>{displayPercent(metric.percent)} <em>total</em></small></MetricSurface>)}</div>

    <section className="portfolio-chart-section"><p className="finance-history-status" role="status">{history.loading ? 'Loading daily history - ' : history.error ? history.error : history.daily ? 'Daily closing valuations  -  recorded trades and FX  -  value changes include cash flows' : 'Recorded valuations'}</p><div className="chart-mode-row"><div><button className={valueMode === 'Amount' ? 'active' : ''} onClick={() => setValueMode('Amount')}>Amount</button><button className={valueMode === 'Percent' ? 'active' : ''} onClick={() => { setValueMode('Percent'); setChartType('Line') }}>Percent</button></div>{valueMode === 'Amount' && <div><button className={chartType === 'Line' ? 'active' : ''} onClick={() => setChartType('Line')}>Line</button><button className={chartType === 'Bar' ? 'active' : ''} onClick={() => setChartType('Bar')}>Bar</button></div>}{valueMode === 'Amount' && chartType === 'Bar' && <div className="granularity-toggle">{(['D','M','Y'] as const).map((item) => <button key={item} className={granularity === item ? 'active' : ''} onClick={() => setGranularity(item)}>{item}</button>)}</div>}</div>
      {!['portfolio','income'].includes(activeMetric) ? <div className="portfolio-chart-empty"><EmptyState title="Historical return components are not available" description="Use Portfolio Value for recorded history or Income Return for recorded payments. The totals above use current holdings and imported income."/></div> : renderedChartData.length > 1 ? <FinanceChart resolution={history.daily ? 'daily' : 'recorded'} points={renderedChartData.map(item => ({ date: item.date, value: chartType === 'Bar' && valueMode === 'Amount' ? item.change : valueMode === 'Percent' ? item.percent : item.value_aud, measurementValue: chartType === 'Bar' && valueMode === 'Amount' ? item.change : item.value_aud }))} label={chartType === 'Bar' ? 'Change' : 'Portfolio'} bars={chartType === 'Bar' && valueMode === 'Amount'} formatValue={v => valueMode === 'Percent' ? `${v.toFixed(2)} pts` : money(v, 'AUD', 2)} formatAxis={v => valueMode === 'Percent' ? `${v.toFixed(0)}%` : `$${Intl.NumberFormat('en', { notation: 'compact', maximumFractionDigits: 1 }).format(v)}`}/> : <div className="portfolio-chart-empty"><EmptyState icon={TrendingUp} title="Performance history begins after your first sync" description="Daily portfolio snapshots will build the return chart without inventing historical values."/></div>}<div className="finance-periods" aria-label="Portfolio chart period">{[['1M','Last 30 Days'],['6M','Last 6 Months'],['1Y','Last 1 Year'],['MAX','All Time']].map(([label, value]) => <button key={value} aria-pressed={range === value} onClick={() => setRange(value)}>{label}</button>)}</div></section>

    <section className="portfolio-holdings"><div className="holdings-head"><h2>Holdings</h2><div><div className="control-popover-wrap"><button className="with-tooltip" data-tooltip="Group by Category" aria-label={groupBy} aria-expanded={groupOpen} onClick={() => setGroupOpen(!groupOpen)}>{groupBy}<ChevronDown size={13}/></button><MotionPopover open={groupOpen} className="control-menu">{(['Exchange','Sector','Currency','Holding Type'] as GroupBy[]).map((item) => <button key={item} onClick={() => { setGroupBy(item); setCollapsedGroups(new Set()); setGroupOpen(false) }}>{groupBy === item && <Check size={13}/>}<span>{item}</span></button>)}</MotionPopover></div><button className={`${hideClosed ? 'active-control ' : ''}with-tooltip tooltip-wide`} data-tooltip="Hide or show closed positions in the table only. Totals and returns do not change." aria-label="Hide Closed" aria-pressed={hideClosed} onClick={() => setHideClosed(!hideClosed)}><EyeOff size={14}/>Hide Closed</button><button className="with-tooltip" data-tooltip="Column Settings" aria-label="Columns" aria-expanded={columnsOpen} onClick={() => { setPendingColumns(visibleColumns); setColumnSearch(''); setColumnsOpen(true) }}><Columns3 size={14}/>Columns</button><div className="control-popover-wrap"><button aria-expanded={exportOpen} onClick={() => setExportOpen(!exportOpen)}><Download size={14}/>Export<ChevronDown size={13}/></button><MotionPopover open={exportOpen} className="control-menu export-menu"><button onClick={() => { exportHoldings(); setExportOpen(false) }}><Download size={14}/><span>CSV</span></button><button onClick={() => { window.print(); setExportOpen(false) }}><Printer size={14}/><span>PDF</span></button></MotionPopover></div></div></div>
      {groups.length ? <div className="portfolio-table-scroll"><table><thead><tr><th aria-sort={sort.key === 'symbol' ? sort.direction : 'none'}><button onClick={() => toggleSort('symbol')}>Symbol{sort.key === 'symbol' ? (sort.direction === 'ascending' ? <ArrowUp size={11}/> : <ArrowDown size={11}/>) : null}</button></th>{visibleColumns.map(headerFor)}<th/></tr></thead><tbody>{groups.map(([market, items]) => { const value = items.reduce((sum,item) => sum + item.value_aud,0); const gain = items.reduce((sum,item) => sum + item.unrealised_gain_aud,0); const cost = items.reduce((sum,item) => sum + item.cost_aud,0); const income = items.reduce((sum,item) => sum + recordedHoldingIncome(item,bundle.transactions),0); const collapsed = collapsedGroups.has(market); return <Fragment key={market}><tr className="market-row"><td colSpan={visibleColumns.length + 2}><button aria-expanded={!collapsed} onClick={() => setCollapsedGroups((current) => { const next = new Set(current); if (next.has(market)) next.delete(market); else next.add(market); return next })}>{collapsed ? <ChevronRight size={13}/> : <ChevronDown size={13}/>}<span>{market}</span></button></td></tr>{!collapsed && <>{items.map((item) => <HoldingRow key={`${item.account_name}-${item.symbol}`} item={item} income={recordedHoldingIncome(item, bundle.transactions)} visibleColumns={visibleColumns} menuOpen={rowMenu === `${item.account_name}-${item.symbol}`} onMenu={() => setRowMenu(rowMenu === `${item.account_name}-${item.symbol}` ? null : `${item.account_name}-${item.symbol}`)}/>)}<tr className="subtotal-row"><td>Total</td>{visibleColumns.map((key) => <td key={key} className={`numeric ${positiveColumn(key) ? (gain >= 0 ? 'positive' : 'negative') : ''}`}>{key === 'value' ? money(value,'AUD',2) : key === 'capital_gain' ? money(gain,'AUD',2) : key === 'income_return' ? money(income,'AUD',2) : key === 'total_return' ? money(gain+income,'AUD',2) : key === 'capital_gain_pct' ? displayPercent(cost ? gain/cost*100 : 0) : key === 'total_return_pct' ? displayPercent(cost ? (gain+income)/cost*100 : 0) : ''}</td>)}<td/></tr></>}</Fragment> })}<tr className="grand-total"><td>Grand Total</td>{visibleColumns.map((key) => <td key={key} className={`numeric ${positiveColumn(key) ? (totalReturn >= 0 ? 'positive' : 'negative') : ''}`}>{key === 'value' ? money(summary.invested,'AUD',2) : key === 'capital_gain' ? money(summary.unrealised,'AUD',2) : key === 'capital_gain_pct' ? displayPercent(summary.returnPct) : key === 'total_return' ? money(totalReturn,'AUD',2) : key === 'total_return_pct' ? displayPercent(totalReturnPct) : ''}</td>)}<td/></tr></tbody></table></div> : <EmptyState title="No holdings match" description="Clear your search or filters, or import a portfolio to populate this table."/>}<p className="portfolio-footnote">* All values displayed in AUD unless otherwise specified.</p></section>

    <MotionDialogSurface open={columnsOpen} className="column-settings" labelledBy="column-settings-title" onClose={() => setColumnsOpen(false)}><header><div><h2 id="column-settings-title">Column Settings</h2><p>Select which columns to display in the holdings table</p></div><button aria-label="Close column settings" onClick={() => setColumnsOpen(false)}><X size={17}/></button></header><label><Search size={15}/><input value={columnSearch} onChange={(event) => setColumnSearch(event.target.value)} placeholder="Search columns…"/></label><div className="column-list"><label className="fixed-column"><LockKeyhole size={12}/><input aria-label="Symbol (w/ name)" type="checkbox" disabled/><span>Symbol (w/ name)</span><small>Fixed</small></label><label className="fixed-column"><LockKeyhole size={12}/><input aria-label="Symbol" type="checkbox" checked readOnly/><span>Symbol</span><small>Fixed</small></label>{columns.filter((item) => item.label.toLowerCase().includes(columnSearch.toLowerCase())).map((item) => <label key={item.key} draggable={pendingColumns.includes(item.key)} onDragStart={() => setDraggedColumn(item.key)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorderColumn(item.key)}><GripVertical className="column-grip" size={12}/><input aria-label={item.label} type="checkbox" checked={pendingColumns.includes(item.key)} onChange={() => togglePendingColumn(item.key)}/><span>{item.label}</span><small className={pendingColumns.includes(item.key) ? 'visible' : ''}>{pendingColumns.includes(item.key) ? 'Visible' : 'Hidden'}</small></label>)}</div><p className="column-reorder-help">Drag selected columns to reorder them</p><footer><button onClick={() => setPendingColumns(defaultColumns)}>Reset to Default</button><span/><button onClick={() => setColumnsOpen(false)}>Cancel</button><button className="apply-columns" onClick={() => { setVisibleColumns(pendingColumns); setColumnsOpen(false) }}>Apply Changes</button></footer></MotionDialogSurface>
  </div>
}
