import { ArrowDown, ArrowUp, CalendarDays, Check, ChevronDown, ChevronRight, Columns3, Download, EyeOff, Filter, MoreHorizontal, Printer, RefreshCw, Search, TrendingUp, X } from 'lucide-react'
import { Fragment, useMemo, useState } from 'react'
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { useNavigate } from 'react-router-dom'
import { usePortfolio } from '../context/PortfolioContext'
import { summarisePortfolio } from '../lib/portfolio'
import { date, downloadCsv, money } from '../lib/format'
import { EmptyState, PrivateMoney } from '../components/ui'
import type { Position } from '../types'

type GroupBy = 'Exchange' | 'Sector' | 'Currency' | 'Holding Type'
type SortKey = 'symbol' | 'current_price' | 'quantity' | 'value_aud' | 'unrealised_gain_aud' | 'return_pct'
type FilterField = '' | GroupBy
type PortfolioFilter = { id: number; field: FilterField; operator: 'is' | 'is not'; value: string }
type ColumnKey = 'price' | 'average_cost' | 'quantity' | 'value' | 'capital_gain' | 'capital_gain_pct' | 'income_return' | 'income_return_pct' | 'currency_gain' | 'currency_gain_pct' | 'total_return' | 'total_return_pct'

const rangeOptions: Record<string, number> = {
  Today: 1, 'Today (from yesterday open)': 2, 'Last 7 Days': 7, 'Last 30 Days': 30,
  'This Month': 31, 'Last Month': 62, 'Current calendar year': 366, 'Previous calendar year': 732,
  'Last 1 Year': 366, 'This Financial year': 366, 'Last Financial year': 732, 'All Time': Infinity,
}

const columns: { key: ColumnKey; label: string; defaultVisible: boolean }[] = [
  { key: 'price', label: 'Price', defaultVisible: true }, { key: 'average_cost', label: 'Avg Buy Price', defaultVisible: false },
  { key: 'quantity', label: 'Quantity', defaultVisible: true }, { key: 'value', label: 'Value', defaultVisible: true },
  { key: 'capital_gain', label: 'Capital Gain', defaultVisible: true }, { key: 'capital_gain_pct', label: 'Capital Gain % (p.a.)', defaultVisible: true },
  { key: 'income_return', label: 'Income Return', defaultVisible: false }, { key: 'income_return_pct', label: 'Income Return % (p.a.)', defaultVisible: false },
  { key: 'currency_gain', label: 'Currency Gain', defaultVisible: false }, { key: 'currency_gain_pct', label: 'Currency Gain % (p.a.)', defaultVisible: false },
  { key: 'total_return', label: 'Total Return', defaultVisible: true }, { key: 'total_return_pct', label: 'Total Return % (p.a.)', defaultVisible: true },
]

const displayPercent = (value: number) => `${Number(value || 0).toFixed(2)}%`
const groupValue = (item: Position, groupBy: GroupBy) => ({ Exchange: item.market, Sector: item.sector, Currency: item.currency, 'Holding Type': item.asset_class }[groupBy] || 'Other')
const positiveColumn = (key: ColumnKey) => ['capital_gain', 'capital_gain_pct', 'total_return', 'total_return_pct'].includes(key)
const cellValue = (item: Position, key: ColumnKey) => ({
  price: money(item.current_price, item.currency, item.currency === 'AUD' ? 3 : 2), average_cost: money(item.average_cost, item.currency, 2),
  quantity: item.quantity.toLocaleString('en-AU', { maximumFractionDigits: 4 }), value: money(item.value_aud, 'AUD', 2),
  capital_gain: money(item.unrealised_gain_aud, 'AUD', 2), capital_gain_pct: displayPercent(item.return_pct), income_return: money(0, 'AUD', 2),
  income_return_pct: '0.00%', currency_gain: money(0, 'AUD', 2), currency_gain_pct: '0.00%', total_return: money(item.unrealised_gain_aud, 'AUD', 2), total_return_pct: displayPercent(item.return_pct),
}[key])

function HoldingRow({ item, visibleColumns, onSelect, menuOpen, onMenu }: { item: Position; visibleColumns: ColumnKey[]; onSelect: () => void; menuOpen: boolean; onMenu: () => void }) {
  const navigate = useNavigate()
  return <tr>
    <td className="portfolio-symbol"><button className="holding-link" onClick={onSelect}><span className="holding-avatar">{item.symbol.slice(0, 1)}</span><span><strong>{item.symbol}</strong><small>{item.name || item.account_name}</small></span></button></td>
    {visibleColumns.map((key) => <td key={key} className={`numeric ${['value','capital_gain','income_return','currency_gain','total_return'].includes(key) ? 'private-value' : ''} ${positiveColumn(key) ? (item.unrealised_gain_aud >= 0 ? 'positive' : 'negative') : ''}`}><span className={key === 'price' ? 'holding-price' : ''}>{cellValue(item, key)}</span></td>)}
    <td className="row-menu"><button aria-label={`Actions for ${item.symbol}`} aria-expanded={menuOpen} onClick={onMenu}><MoreHorizontal size={15}/></button>{menuOpen && <div className="row-menu-popover"><button onClick={onSelect}>View holding</button><button onClick={() => navigate(`/app/transactions?symbol=${encodeURIComponent(item.symbol)}`)}>View transactions</button></div>}</td>
  </tr>
}

export function Overview() {
  const { bundle, action, refreshQuotes } = usePortfolio()
  const [query, setQuery] = useState(''); const [range, setRange] = useState('All Time'); const [rangeOpen, setRangeOpen] = useState(false); const [customStart, setCustomStart] = useState(bundle.snapshots[0]?.date || ''); const [customEnd, setCustomEnd] = useState(bundle.snapshots.at(-1)?.date || '')
  const [positionsOpen, setPositionsOpen] = useState(false); const [positionsMode, setPositionsMode] = useState<'All Positions' | 'Open Positions Only'>('All Positions')
  const [filterOpen, setFilterOpen] = useState(false); const [filters, setFilters] = useState<PortfolioFilter[]>([])
  const [valueMode, setValueMode] = useState<'Amount' | 'Percent'>('Amount'); const [chartType, setChartType] = useState<'Line' | 'Bar'>('Line'); const [granularity, setGranularity] = useState<'D' | 'M' | 'Y'>('M')
  const [groupBy, setGroupBy] = useState<GroupBy>('Exchange'); const [groupOpen, setGroupOpen] = useState(false); const [collapsedGroups, setCollapsedGroups] = useState<Set<string>>(new Set())
  const [hideClosed, setHideClosed] = useState(false); const [columnsOpen, setColumnsOpen] = useState(false); const [columnSearch, setColumnSearch] = useState('')
  const [visibleColumns, setVisibleColumns] = useState<ColumnKey[]>(columns.filter((item) => item.defaultVisible).map((item) => item.key)); const [draggedColumn, setDraggedColumn] = useState<ColumnKey | null>(null); const [exportOpen, setExportOpen] = useState(false)
  const [sort, setSort] = useState<{ key: SortKey; direction: 'ascending' | 'descending' }>({ key: 'symbol', direction: 'ascending' }); const [rowMenu, setRowMenu] = useState<string | null>(null); const [selectedHolding, setSelectedHolding] = useState<Position | null>(null)
  const summary = useMemo(() => summarisePortfolio(bundle), [bundle])
  const chartData = useMemo(() => { const latest = bundle.snapshots.at(-1)?.date ? new Date(bundle.snapshots.at(-1)!.date).getTime() : 0; const days = rangeOptions[range] ?? Infinity; const rows = bundle.snapshots.filter((item) => { const time = new Date(item.date).getTime(); if (range === 'Custom range') return (!customStart || time >= new Date(customStart).getTime()) && (!customEnd || time <= new Date(customEnd).getTime()); return days === Infinity || time >= latest - days * 86_400_000 }); const first = rows[0]?.value_aud || 0; return rows.map((item, index) => ({ ...item, percent: first ? ((item.value_aud - first) / first) * 100 : 0, change: index ? item.value_aud - rows[index - 1].value_aud : 0 })) }, [bundle.snapshots, customEnd, customStart, range])
  const renderedChartData = useMemo(() => { if (chartType !== 'Bar' || granularity === 'D') return chartData; const buckets = new Map<string, (typeof chartData)[number]>(); chartData.forEach((item) => { const parsed = new Date(item.date); const key = granularity === 'Y' ? String(parsed.getFullYear()) : `${parsed.getFullYear()}-${parsed.getMonth()}`; buckets.set(key, item) }); const rows = [...buckets.values()]; return rows.map((item, index) => ({ ...item, change: index ? item.value_aud - rows[index - 1].value_aud : 0 })) }, [chartData, chartType, granularity])
  const filtered = useMemo(() => bundle.holdings.filter((item) => { if (!`${item.symbol} ${item.name} ${item.market} ${item.account_name}`.toLowerCase().includes(query.toLowerCase())) return false; if ((positionsMode === 'Open Positions Only' || hideClosed) && item.quantity <= 0) return false; return filters.every((filter) => { if (!filter.field || !filter.value) return true; const matches = groupValue(item, filter.field).toLowerCase() === filter.value.toLowerCase(); return filter.operator === 'is' ? matches : !matches }) }), [bundle.holdings, filters, hideClosed, positionsMode, query])
  const groups = useMemo(() => { const output = new Map<string, Position[]>(); filtered.forEach((item) => { const key = groupValue(item, groupBy); output.set(key, [...(output.get(key) || []), item]) }); const direction = sort.direction === 'ascending' ? 1 : -1; return [...output.entries()].map(([key, items]) => [key, [...items].sort((a, b) => { const av = a[sort.key]; const bv = b[sort.key]; return (typeof av === 'string' ? av.localeCompare(String(bv)) : Number(av) - Number(bv)) * direction })] as [string, Position[]]) }, [filtered, groupBy, sort])
  const totalReturn = summary.unrealised + summary.income; const totalReturnPct = summary.cost ? (totalReturn / summary.cost) * 100 : 0
  const addFilter = () => setFilters((current) => [...current, { id: Date.now(), field: '', operator: 'is', value: '' }]); const updateFilter = (id: number, changes: Partial<PortfolioFilter>) => setFilters((current) => current.map((item) => item.id === id ? { ...item, ...changes } : item))
  const toggleSort = (key: SortKey) => setSort((current) => ({ key, direction: current.key === key && current.direction === 'ascending' ? 'descending' : 'ascending' })); const toggleColumn = (key: ColumnKey) => setVisibleColumns((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key])
  const reorderColumn = (target: ColumnKey) => { if (!draggedColumn || draggedColumn === target || !visibleColumns.includes(draggedColumn) || !visibleColumns.includes(target)) return; setVisibleColumns((current) => { const next = current.filter((item) => item !== draggedColumn); next.splice(next.indexOf(target), 0, draggedColumn); return next }); setDraggedColumn(null) }
  const exportHoldings = () => downloadCsv('masterdeck-holdings.csv', ['Symbol', 'Market', 'Price', 'Quantity', 'Value AUD', 'Capital gain AUD', 'Capital gain %'], filtered.map((item) => [item.symbol, item.market, item.current_price, item.quantity, item.value_aud, item.unrealised_gain_aud, item.return_pct])); const getFilterValues = (field: FilterField) => field ? [...new Set(bundle.holdings.map((item) => groupValue(item, field)))].sort() : []
  const headerFor = (key: ColumnKey) => { const def = columns.find((item) => item.key === key)!; const sortKey: SortKey = ({ price: 'current_price', average_cost: 'current_price', quantity: 'quantity', value: 'value_aud', capital_gain: 'unrealised_gain_aud', capital_gain_pct: 'return_pct', income_return: 'unrealised_gain_aud', income_return_pct: 'return_pct', currency_gain: 'unrealised_gain_aud', currency_gain_pct: 'return_pct', total_return: 'unrealised_gain_aud', total_return_pct: 'return_pct' })[key] as SortKey; return <th key={key} className="numeric" aria-sort={sort.key === sortKey ? sort.direction : 'none'}><button onClick={() => toggleSort(sortKey)}>{def.label}{sort.key === sortKey ? (sort.direction === 'ascending' ? <ArrowUp size={11}/> : <ArrowDown size={11}/>) : null}</button></th> }

  return <div className="portfolio-page">
    <div className="portfolio-toolbar"><label className="portfolio-filter"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Filter holdings…" aria-label="Filter holdings"/></label>
      <div className="control-popover-wrap"><button aria-expanded={rangeOpen} onClick={() => setRangeOpen(!rangeOpen)}><CalendarDays size={15}/>{range}<ChevronDown size={13}/></button>{rangeOpen && <div className="control-menu range-menu" role="menu">{[...Object.keys(rangeOptions), 'Custom range'].map((item) => <button key={item} className={range === item ? 'selected' : ''} onClick={() => { setRange(item); setRangeOpen(false) }}>{range === item && <Check size={13}/>}<span>{item}</span></button>)}</div>}</div>
      <button className={filterOpen ? 'active-control' : ''} aria-expanded={filterOpen} onClick={() => { setFilterOpen(!filterOpen); if (!filters.length) addFilter() }}><Filter size={15}/>Filter{filters.filter((item) => item.field && item.value).length > 0 && <span className="filter-count">{filters.filter((item) => item.field && item.value).length}</span>}</button>
      <div className="control-popover-wrap"><button aria-expanded={positionsOpen} onClick={() => setPositionsOpen(!positionsOpen)}>{positionsMode}<ChevronDown size={13}/></button>{positionsOpen && <div className="control-menu">{(['All Positions','Open Positions Only'] as const).map((item) => <button key={item} onClick={() => { setPositionsMode(item); setPositionsOpen(false) }}>{positionsMode === item && <Check size={13}/>}<span>{item}</span></button>)}</div>}</div>
      <button className="refresh-market" onClick={() => refreshQuotes()} disabled={action === 'refresh-quotes'}><RefreshCw className={action === 'refresh-quotes' ? 'spin' : ''} size={15}/>Refresh</button></div>
    {range === 'Custom range' && <section className="custom-range" aria-label="Custom date range"><label>From<input type="date" value={customStart} max={customEnd || undefined} onChange={(event) => setCustomStart(event.target.value)}/></label><label>To<input type="date" value={customEnd} min={customStart || undefined} onChange={(event) => setCustomEnd(event.target.value)}/></label></section>}
    {filterOpen && <section className="filter-builder" aria-label="Portfolio filters"><span>Where</span>{filters.map((filter) => <div className="filter-row" key={filter.id}><select aria-label="Filter field" value={filter.field} onChange={(event) => updateFilter(filter.id, { field: event.target.value as FilterField, value: '' })}><option value="">Select field…</option>{(['Exchange','Sector','Currency','Holding Type'] as GroupBy[]).map((item) => <option key={item}>{item}</option>)}</select><select aria-label="Filter operator" disabled={!filter.field} value={filter.operator} onChange={(event) => updateFilter(filter.id, { operator: event.target.value as PortfolioFilter['operator'] })}><option>is</option><option>is not</option></select><select aria-label="Filter value" disabled={!filter.field} value={filter.value} onChange={(event) => updateFilter(filter.id, { value: event.target.value })}><option value="">Select value…</option>{getFilterValues(filter.field).map((item) => <option key={item}>{item}</option>)}</select><button aria-label="Remove filter" onClick={() => setFilters((current) => current.filter((item) => item.id !== filter.id))}><X size={14}/></button></div>)}<button className="add-filter" onClick={addFilter}>+ Add filter</button></section>}

    <div className="portfolio-metrics"><div><span>Portfolio Value</span><strong><PrivateMoney value={summary.total} digits={2}/></strong><small className={totalReturnPct >= 0 ? 'positive' : 'negative'}>{displayPercent(totalReturnPct)} <em>p.a.</em></small></div><div><span>Capital Gain</span><strong><PrivateMoney value={summary.unrealised} digits={2}/></strong><small className={summary.returnPct >= 0 ? 'positive' : 'negative'}>{displayPercent(summary.returnPct)} <em>p.a.</em></small></div><div><span>Income Return</span><strong><PrivateMoney value={summary.income} digits={2}/></strong><small className="positive">{summary.cost ? displayPercent(summary.income / summary.cost * 100) : '0.00%'} <em>p.a.</em></small></div><div><span>Currency Gain</span><strong>$0.00</strong><small>0.00% <em>p.a.</em></small></div><div className="active"><span>Total Return</span><strong><PrivateMoney value={totalReturn} digits={2}/></strong><small className={totalReturnPct >= 0 ? 'positive' : 'negative'}>{displayPercent(totalReturnPct)} <em>p.a.</em></small></div></div>

    <section className="portfolio-chart-section"><div className="chart-mode-row"><div><button className={valueMode === 'Amount' ? 'active' : ''} onClick={() => setValueMode('Amount')}>Amount</button><button className={valueMode === 'Percent' ? 'active' : ''} onClick={() => { setValueMode('Percent'); setChartType('Line') }}>Percent</button></div>{valueMode === 'Amount' && <div><button className={chartType === 'Line' ? 'active' : ''} onClick={() => setChartType('Line')}>Line</button><button className={chartType === 'Bar' ? 'active' : ''} onClick={() => setChartType('Bar')}>Bar</button></div>}{valueMode === 'Amount' && chartType === 'Bar' && <div className="granularity-toggle">{(['D','M','Y'] as const).map((item) => <button key={item} className={granularity === item ? 'active' : ''} onClick={() => setGranularity(item)}>{item}</button>)}</div>}</div>
      {renderedChartData.length > 1 ? <div className="portfolio-main-chart"><ResponsiveContainer width="100%" height="100%">{chartType === 'Bar' && valueMode === 'Amount' ? <BarChart data={renderedChartData} margin={{top:18,right:12,left:0,bottom:0}}><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="date" tickFormatter={(value) => date(value,{month:'short'})} axisLine={false} tickLine={false}/><YAxis orientation="right" tickFormatter={(value) => `$${Math.round(Number(value)/1000)}k`} axisLine={false} tickLine={false} width={56}/><Tooltip formatter={(value) => money(Number(value),'AUD',2)}/><Bar dataKey="change" isAnimationActive={false}>{renderedChartData.map((item,index) => <Cell key={index} fill={item.change >= 0 ? '#24a36a' : '#dc5a62'}/>)}</Bar></BarChart> : <AreaChart data={renderedChartData} margin={{top:18,right:12,left:0,bottom:0}}><defs><linearGradient id="portfolio-blue-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#3a6ff5" stopOpacity={0.16}/><stop offset="1" stopColor="#3a6ff5" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--line)" vertical={false}/><XAxis dataKey="date" tickFormatter={(value) => date(value,{month:'short'})} axisLine={false} tickLine={false}/><YAxis orientation="right" tickFormatter={(value) => valueMode === 'Percent' ? `${Number(value).toFixed(0)}%` : `$${Math.round(Number(value)/1000)}k`} axisLine={false} tickLine={false} width={56}/><Tooltip formatter={(value) => valueMode === 'Percent' ? displayPercent(Number(value)) : money(Number(value),'AUD',2)}/><Area type="linear" dataKey={valueMode === 'Percent' ? 'percent' : 'value_aud'} stroke="#3a6ff5" strokeWidth={2} fill="url(#portfolio-blue-fill)" dot={false} isAnimationActive={false}/></AreaChart>}</ResponsiveContainer></div> : <div className="portfolio-chart-empty"><EmptyState icon={TrendingUp} title="Performance history begins after your first sync" description="Daily portfolio snapshots will build the return chart without inventing historical values."/></div>}</section>

    <section className="portfolio-holdings"><div className="holdings-head"><h2>Holdings</h2><div><div className="control-popover-wrap"><button aria-expanded={groupOpen} onClick={() => setGroupOpen(!groupOpen)}>{groupBy}<ChevronDown size={13}/></button>{groupOpen && <div className="control-menu">{(['Exchange','Sector','Currency','Holding Type'] as GroupBy[]).map((item) => <button key={item} onClick={() => { setGroupBy(item); setCollapsedGroups(new Set()); setGroupOpen(false) }}>{groupBy === item && <Check size={13}/>}<span>{item}</span></button>)}</div>}</div><button className={hideClosed ? 'active-control' : ''} aria-pressed={hideClosed} onClick={() => setHideClosed(!hideClosed)}><EyeOff size={14}/>Hide Closed</button><button aria-expanded={columnsOpen} onClick={() => setColumnsOpen(true)}><Columns3 size={14}/>Columns</button><div className="control-popover-wrap"><button aria-expanded={exportOpen} onClick={() => setExportOpen(!exportOpen)}><Download size={14}/>Export<ChevronDown size={13}/></button>{exportOpen && <div className="control-menu export-menu"><button onClick={() => { window.print(); setExportOpen(false) }}><Printer size={14}/><span>PDF</span></button><button onClick={() => { exportHoldings(); setExportOpen(false) }}><Download size={14}/><span>CSV</span></button></div>}</div></div></div>
      {groups.length ? <div className="portfolio-table-scroll"><table><thead><tr><th aria-sort={sort.key === 'symbol' ? sort.direction : 'none'}><button onClick={() => toggleSort('symbol')}>Symbol{sort.key === 'symbol' ? (sort.direction === 'ascending' ? <ArrowUp size={11}/> : <ArrowDown size={11}/>) : null}</button></th>{visibleColumns.map(headerFor)}<th/></tr></thead><tbody>{groups.map(([market, items]) => { const value = items.reduce((sum,item) => sum + item.value_aud,0); const gain = items.reduce((sum,item) => sum + item.unrealised_gain_aud,0); const cost = items.reduce((sum,item) => sum + item.cost_aud,0); const collapsed = collapsedGroups.has(market); return <Fragment key={market}><tr className="market-row"><td colSpan={visibleColumns.length + 2}><button aria-expanded={!collapsed} onClick={() => setCollapsedGroups((current) => { const next = new Set(current); if (next.has(market)) next.delete(market); else next.add(market); return next })}>{collapsed ? <ChevronRight size={13}/> : <ChevronDown size={13}/>}<span>{market}</span></button></td></tr>{!collapsed && <>{items.map((item) => <HoldingRow key={`${item.account_name}-${item.symbol}`} item={item} visibleColumns={visibleColumns} onSelect={() => setSelectedHolding(item)} menuOpen={rowMenu === `${item.account_name}-${item.symbol}`} onMenu={() => setRowMenu(rowMenu === `${item.account_name}-${item.symbol}` ? null : `${item.account_name}-${item.symbol}`)}/>)}<tr className="subtotal-row"><td>Total</td>{visibleColumns.map((key) => <td key={key} className={`numeric ${positiveColumn(key) ? (gain >= 0 ? 'positive' : 'negative') : ''}`}>{key === 'value' ? money(value,'AUD',2) : key === 'capital_gain' || key === 'total_return' ? money(gain,'AUD',2) : key === 'capital_gain_pct' || key === 'total_return_pct' ? displayPercent(cost ? gain/cost*100 : 0) : ''}</td>)}<td/></tr></>}</Fragment> })}<tr className="grand-total"><td>Grand Total</td>{visibleColumns.map((key) => <td key={key} className={`numeric ${positiveColumn(key) ? (totalReturn >= 0 ? 'positive' : 'negative') : ''}`}>{key === 'value' ? money(summary.invested,'AUD',2) : key === 'capital_gain' ? money(summary.unrealised,'AUD',2) : key === 'capital_gain_pct' ? displayPercent(summary.returnPct) : key === 'total_return' ? money(totalReturn,'AUD',2) : key === 'total_return_pct' ? displayPercent(totalReturnPct) : ''}</td>)}<td/></tr></tbody></table></div> : <EmptyState title="No holdings match" description="Clear your search or filters, or import a portfolio to populate this table."/>}<p className="portfolio-footnote">* All values displayed in AUD unless otherwise specified.</p></section>

    {columnsOpen && <div className="modal-backdrop" onMouseDown={() => setColumnsOpen(false)}><section className="column-settings" role="dialog" aria-modal="true" aria-labelledby="column-settings-title" onMouseDown={(event) => event.stopPropagation()}><header><div><h2 id="column-settings-title">Column Settings</h2><p>Select which columns to display in the holdings table</p></div><button aria-label="Close column settings" onClick={() => setColumnsOpen(false)}><X size={17}/></button></header><label><Search size={15}/><input value={columnSearch} onChange={(event) => setColumnSearch(event.target.value)} placeholder="Search columns…"/></label><div className="column-list">{columns.filter((item) => item.label.toLowerCase().includes(columnSearch.toLowerCase())).map((item) => <label key={item.key} draggable={visibleColumns.includes(item.key)} onDragStart={() => setDraggedColumn(item.key)} onDragOver={(event) => event.preventDefault()} onDrop={() => reorderColumn(item.key)}><input type="checkbox" checked={visibleColumns.includes(item.key)} onChange={() => toggleColumn(item.key)}/><span>{item.label}</span></label>)}</div><footer>Drag selected columns to reorder them</footer></section></div>}
    {selectedHolding && <div className="modal-backdrop" onMouseDown={() => setSelectedHolding(null)}><section className="holding-detail" role="dialog" aria-modal="true" aria-labelledby="holding-detail-title" onMouseDown={(event) => event.stopPropagation()}><header><div className="holding-avatar">{selectedHolding.symbol.slice(0,1)}</div><div><h2 id="holding-detail-title">{selectedHolding.symbol}</h2><p>{selectedHolding.name || selectedHolding.account_name}</p></div><button aria-label="Close holding details" onClick={() => setSelectedHolding(null)}><X size={17}/></button></header><dl><div><dt>Account</dt><dd>{selectedHolding.account_name}</dd></div><div><dt>Quantity</dt><dd>{selectedHolding.quantity.toLocaleString('en-AU')}</dd></div><div><dt>Price</dt><dd>{money(selectedHolding.current_price, selectedHolding.currency,2)}</dd></div><div><dt>Market value</dt><dd>{money(selectedHolding.value_aud,'AUD',2)}</dd></div><div><dt>Capital gain</dt><dd className={selectedHolding.unrealised_gain_aud >= 0 ? 'positive' : 'negative'}>{money(selectedHolding.unrealised_gain_aud,'AUD',2)}</dd></div><div><dt>Total return</dt><dd className={selectedHolding.return_pct >= 0 ? 'positive' : 'negative'}>{displayPercent(selectedHolding.return_pct)}</dd></div></dl></section></div>}
  </div>
}
